name: unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        experimental: [false]
        exclude:
          #  lxml built-from-source fails or produces unreliable results on these platforms
          # ... so skip these platforms, and include with experimental flag
          - os: windows-latest
            python-version: "3.11"
          # include the problematic platforms with experimental flag set true
          # that way we can observe them and them failing won't mark the whole workflow as a fail
        include:
          - os: windows-latest
            python-version: "3.11"
            experimental: true
          # mark toxenv as py-darwin on macos (check tox.ini)
          - toxenv: py
          - os: macos-latest
            toxenv: py-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox -e ${{ matrix.toxenv }}
      # Provide code coverage reports on Linux
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: coveralls.io
        uses: AndreMiras/coveralls-python-action@develop
        with:
          # coveralls repo token
          github-token: "SmlfzlVJy4ow55rduU7IU5GmmFCfAdGeq"
